### ISSUE TITLE
Duplicate API Go Client on Documentation

### ISSUE THREAD

**Issue by victorshinya** [afuh/rick-and-morty-api-site#38]
Looking into the documentation, I found out that there are two items for Go Client, one after Elixir and the other one after Ruby. I didn't find the same thing on [documentation.md](https://github.com/afuh/rick-and-morty-api-site/blob/develop/src/pages/documentation.md). But as this is an improvement for the website documentation, it is better to update it as well.

**Comment by afuh** [comment]
fixed it! 
Thanks for the heads up.
