### ISSUE TITLE
Issue with HTTP/2 301 characters endpoint

### ISSUE THREAD

**Issue by RogerOrdonez** [afuh/rick-and-morty-api-site#50]
Hi... i am practicing to request the characters endpoint: https://rickandmortyapi.com/api/character through an API Gataway that i am learning how to implement it. With the episodes and locations endpoints all work fine. With the character endpoint i have an issue with my API Gateway beacause the character API is responding first with a HTTP 301 code and then with a HTTP 200 code. Please fix it and standarize it with the other two endpoints (locations and episodes) that just reponse with HTTP 200 code.

Best regards.

![rick](https://user-images.githubusercontent.com/28494845/87707278-19af6600-c75e-11ea-8926-01ba6920465e.png)

**Comment by afuh** [comment]
Hi, 
this is the website, not the [API](https://github.com/afuh/rick-and-morty-api). 
In any case, PRs are welcome. 

Best!
