### ISSUE TITLE
Donate button redirect 404

### ISSUE THREAD

**Issue by bettse** [afuh/rick-and-morty-api-site#56]
After donating, I was redirected to `/helps-us/thank-you`(note the 's' in 'helps'), which returns a 404.  I think the correct url is `/help-us/thank-you`.  I didn't see a result when searching this repo, so I'm guessing that the URL is a part of the configuration at the donation service.

**Comment by afuh** [comment]
Hey @bettse,
thank you for the donation!! and thank you for the heads up with the `url`. 
Since you are the first person to donate, you are probably the first to see that `404` 🙂

Thanks again, with your donation we are going to pay the Netlify bandwidth extra usage for this month!

**Comment by bettse** [comment]
Tried to test this and I think you're using a new donation platform, so I'm going to close it as fixed.
